'DIRNAME': 'ref'
'LIBRARY_DIRNAME': 'python'
'DIRNAMES_TO_TITLES':
  'ref': 'Reference'
  'cli': 'Command Line Interface'
  'data-types': 'Data Types'
  'public-api': 'Import & Export API'
  'python': 'Python Library'
  'integrations': 'Integrations'
  'java': 'Java Library \[Beta\]'
  'keras': 'Keras'
'SKIPS':
    - 'app'
    - 'java'
'WANDB_DATATYPES':
  - 'Graph'
  - 'Image'
  - 'Plotly'
  - 'Video'
  - 'Audio'
  - 'Table'
  - 'Html'
  - 'Object3D'
  - 'Molecule'
  - 'Histogram'
'WANDB_API':
  - 'Api'
  - 'Projects'
  - 'Project'
  - 'Runs'
  - 'Run'
  - 'Sweep'
  - 'Files'
  - 'File'
  - 'Artifact'
'WANDB_INTEGRATIONS':
  - 'keras'
  # - 'sklearn'
  # - 'gym'
  # - 'lightgbm'
  # - 'sacred'
  # - 'tensorflow'
  # - 'tensorboard'
  # - 'xgboost'
  # - 'fastai'
  # - 'torch'
  # - 'sagemaker'